# If the version contains the SNAPSHOT suffix it will run publishYdwkPublicationToMavenCentralRepository
name: Snapshot
on:
  push:
    branches:
      - 'master'

jobs:
  snapshot:
    name: Create Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Read Version
        id: read-version
        run: |
          version=`cat gradle.properties | sed -n "s/^.*ydwkVersion\s*=\s*\(\S*\).*$/\1/p"`
          echo "ydwkVersion<<EOF" >>$GITHUB_OUTPUT
          echo "ydwkVersion" >>$GITHUB_OUTPUT
          echo "EOF" >>$GITHUB_OUTPUT
      - name: Run maven snapshot
        if: ${{ endsWith(steps.read-version.outputs.version, 'SNAPSHOT') }}
        run: |
          ./gradlew publishYdwkPublicationToMavenCentralRepository
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
